[server]
enableCORS = false
enableXsrfProtection = false
address = "0.0.0.0"
port = 8501
headless = true
runOnSave = false

[browser]
gatherUsageStats = false
serverAddress = "78.47.129.250"
serverPort = 8501
